from textwrap import dedent
from typing import Any, Dict

from report.base import BaseReportManager


class EnglishReportManager(BaseReportManager):
    def _formatted_header(self, username: str) -> str:
        return dedent(f"""
            # Welcome to {username}'s Contribution Report
            This report is auto generated by [daily-contribution-checker](https://github.com/lntuition/daily-contribution-checker).
            If you have any question or problem, please report [here](https://github.com/lntuition/daily-contribution-checker/issues).
            I hope this report will be a companion for your contribution trip :airplane:
        """)

    def _formatted_summary(self, **kwargs) -> str:
        return dedent(f"""
            ## Summary
            - **{kwargs["today_date"]}** is **{kwargs["total_length"]}th day** since the start of trip :sweat_smile:
            - There was **{kwargs["today_cnt"] if kwargs["today_cnt"] > 0 else "NO"}** new contribution 
            at **{kwargs["today_date"]}**. {"Good job :+1:" if kwargs["today_cnt"] > 0 else "Cheer up :muscle:"}
            - During the trip, total contribution count is **{kwargs["total_cnt"]}** and average contribution count 
            is **{kwargs["avg_cnt"]:.2f}**
            - Daily maximum contribution day is **{kwargs["max_date"]}**, which is **{kwargs["max_cnt"]}**.
            - Longest continous contribution trip was **{kwargs["max_continous_length"]}** days 
            From **{kwargs["max_continous_start_date"]}** to **{kwargs["max_continous_end_date"]}** :walking:
            - Current continous contribution trip is **{kwargs["cur_continous_length"]}** days 
            From **{kwargs["cur_continous_start_date"]}** :running:
        """)

    def _config_graph(self, **kwargs) -> Dict[str, Any]:
        return {
            "title": "Percentage of daily contribution count",
            "box_title": "Daily contribution count",
        }

    def _config_table(self, **kwargs) -> Dict[str, Any]:
        def formatter(year: int, week: int):
            return f"Week {week} of {year}"

        return {
            "headers": ["DATE", "MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
            "formatter": formatter
        }
