from typing import Iterable, Sequence

from attribute import Graph, Header, Summary


class Setting:
    pass


class EnglishHeaderSetting(Header, Setting):
    @staticmethod
    def title(user: str) -> str:
        return f"Welcome to {user}'s contribution report"

    @staticmethod
    def repository(url: str) -> str:
        return f"This report is generated by [contribution-markdown-report]({url})."

    @staticmethod
    def issue(url: str) -> str:
        return f"If you have any question or problem, please report [here]({url})."

    @staticmethod
    def ending() -> str:
        return "I hope this report will be a companion for your contribution trip."


class EnglishSummarySetting(Summary, Setting):
    @staticmethod
    def title() -> str:
        return "Summary"

    @staticmethod
    def today(date: str, count: str, length: str) -> str:
        return f"{date} was {length}th day since the start of trip, and there was {count} new contribution."

    @staticmethod
    def maximum(date: str, count: str) -> str:
        return f"Daily maximum contribution day is {date}, which is {count}."

    @staticmethod
    def total(_sum: str, avg: str) -> str:
        return f"During the trip, total contribuition count is {_sum} and average contribution count is {avg}."

    @staticmethod
    def peak(length: str, start: str, end: str) -> str:
        return f"Longest continuous contribution trip was {length} days from {start} to {end}."

    @staticmethod
    def cur_peak(length: str, start: str) -> str:
        return f"Current continuous contribution trip is {length} days from {start}."


class EnglishGraphSetting(Graph, Setting):
    @staticmethod
    def title() -> str:
        return "Graph"

    @staticmethod
    def dayofweek_label() -> Sequence[str]:
        return ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

    @staticmethod
    def month_label() -> Sequence[str]:
        return ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

    @staticmethod
    def contribution_axis() -> str:
        return "contribution count"

    @staticmethod
    def day_axis() -> str:
        return "day"

    @staticmethod
    def dayofweek_axis() -> str:
        return "day of week"

    @staticmethod
    def month_axis() -> str:
        return "month"

    @staticmethod
    def count_sum_recent_title() -> str:
        return "Number of days per contribution up to the last 4 weeks"

    @staticmethod
    def count_sum_full_title() -> str:
        return "Number of days per contribution"

    @staticmethod
    def dayofweek_sum_recent_title() -> str:
        return "Number of contribution per day of week up to the last 12 weeks"

    @staticmethod
    def dayofweek_mean_full_title() -> str:
        return "Average of contribution per day of week"

    @staticmethod
    def month_sum_recent_title() -> str:
        return "Number of contribution per month up to the last year"

    @staticmethod
    def month_mean_full_title() -> str:
        return "Average of contribution per month"


class SettingUnsupportedException(Exception):
    pass


class SettingFactory:
    @staticmethod
    def create_settings(language: str) -> Iterable[Setting]:
        if language == "english":  # Default
            return [EnglishHeaderSetting(), EnglishSummarySetting(), EnglishGraphSetting()]

        raise SettingUnsupportedException()
