name: Continous Deployment

on:
  push:
    branches: 
      - master
    paths:
      - "config/*"
      - "src/*"
      - "Dockerfile"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Github actions checkout@v2
        uses: actions/checkout@v2

      - name: Deploy docker images to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lntuition/contribution-markdown-report
          tags: latest
