name: Example for contribution markdown report

on:
  # Github actions will trigger event at saturday 09:00 AM UTC.
  schedule:
    - cron: "0 9 * * SAT"

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
    - uses: lntuition/contribution-markdown-report@master
      with:
        # Branch where the report will be updated, default is default branch
        branch: ""
        # Relative path where the report will be updated, default is ${repository}/result
        workspace: "result"
        # Name of markdown report file, default is README
        file_name: "README"

        # User of report, default is repository owner
        user: "lntuition"
        # Start date in report, following isoformat
        start_date: "2020-07-01"
        # End date in report, default is yesterday. Except for yesterday keyword, following isoformat
        end: "yesterday"
        # Language used in report, default is english
        langugage: "english"
