name: Contribution markdown report

on:
  # Github actions will generate report daily 09:00 AM UTC.
  schedule:
    - cron: "0 9 * * *"

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Contribuition markdown report
      # You should use concrete marketplace version instead of master.
      uses: lntuition/contribution-markdown-report@master
      with:
        # Change below variable to date you want to start tracking.
        start_date: "2020-07-01"
        # Branch where the result will be. Default branch is master.
        branch: "master"
        # Path where the result will be. Default path is "." which is root directory of repo.
        path: "result"
