name: Continuous integration

on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/**
      - contribution-markdown-report/**
      - action.yml
      - Dockerfile
      - Makefile

  pull_request:
    branches: 
      - master
    paths:
      - .github/workflows/**
      - contribution-markdown-report/**
      - action.yml
      - Dockerfile
      - Makefile

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Build docker image"
        run: make build
      - name: "Import check with isort"
        run: make isort
      - name: "Format check with black"
        run: make black
      - name: "Lint checking with pylint"
        run: make pylint
      - name: "Typing check with mypy"
        run: make mypy
      - name: "Unit test"
        run: make unit
      - name: "Integration test"
        run: make integration
      - uses: actions/upload-artifact@v2
        with:
          name: markdown-report
          path: ./output/result
