name: Continuous integration

on:
  push:
    branches: 
      - develop
    paths:
      - .github/config/**
      - .github/workflows/**
      - config/**
      - src/**
      - action.yml
      - Dockerfile
      - Makefile

  pull_request:
    branches:
      - master
    paths:
      - .github/config/**
      - .github/workflows/**
      - config/**
      - src/**
      - action.yml
      - Dockerfile
      - Makefile

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "[SET UP] Setup filter"
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: .github/config/integration_filter.yml
      - name: "[SET UP] Build docker image"
        run: make build

      - name: "[BUILD TEST] Format check - isort"
        run: make test_isort
      - name: "[BUILD TEST] Format check - black"
        run: make test_black
      - name: "[BUILD TEST] Lint check - pylint"
        run: make test_pylint
      - name: "[BUILD TEST] Typing check - mypy"
        run: make test_mypy

      - name: "[UNIT TEST] Unit test - pytest"
        run: make test_pytest

      - name: "[INTEGRATION TEST] Integration test - default"
        run: make artifact \
          USERNAME=${{ github.actor }} \
          LANGUAGE=english \
          START_DATE=2020-07-01 

      - name: "[TEAR DOWN] Upload artifact"
        uses: actions/upload-artifact@v2
        with:
          path: artifact
