name: Continuous integration

on:
  push:
    branches: 
      - develop
    paths:
      - .github/config/**
      - .github/workflows/**
      - config/**
      - src/**
      - action.yml
      - Dockerfile
      - Makefile

  pull_request:
    branches:
      - master
    paths:
      - .github/config/**
      - .github/workflows/**
      - config/**
      - src/**
      - action.yml
      - Dockerfile
      - Makefile

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "[SET UP] Setup filter"
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: .github/config/integration_filter.yml
      - name: "[SET UP] Build docker image"
        run: make build

      - name: "[BUILD TEST] Format check - isort"
        run: make test-isort
      - name: "[BUILD TEST] Format check - black"
        run: make test-black
      - name: "[BUILD TEST] Lint check - pylint"
        run: make test-pylint
      - name: "[BUILD TEST] Typing check - mypy"
        run: make test-mypy

      - name: "[UNIT TEST] Unit test - pytest"
        run: make test-pytest

      - name: Live test
        uses: lntuition/contribution-markdown-report@develop
        with:
          start_date: "2020-07-01"
          branch: "develop"
          path: "result"
