name: Contribution markdown report - test

on:
  push:
    branches: 
     - develop

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Contribution markdown report - live test
      uses: lntuition/contribution-markdown-report@develop
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        start_date: "2020-07-01"
        branch: "develop"
        path: "result"
