from textwrap import dedent

from lib.base.type import ConfigType
from lib.language.base import LanguageSetting


class EnglishSetting(LanguageSetting):
    def format_header(self, config: ConfigType) -> str:
        return dedent(f"""
            # Welcome to {config["username"]}'s Contribution Report
            This report is auto generated by [contribution-markdown-report](https://github.com/lntuition/contribution-markdown-report).
            If you have any question or problem, please report [here](https://github.com/lntuition/contribution-markdown-report/issues).
            I hope this report will be a companion for your contribution trip :airplane:
        """)

    def format_summary(self, config: ConfigType) -> str:
        return dedent(f"""
            ## Summary
            - **{config["today"]["date"]}** is **{config["total"]["length"]}th day** since the start of trip :sweat_smile:
            - There was **{config["today"]["count"] if config["today"]["count"] > 0 else "NO"}** new contribution 
            at **{config["today"]["date"]}**. {"Good job :+1:" if config["today"]["count"] > 0 else "Cheer up :muscle:"}
            - During the trip, total contribution count is **{config["total"]["sum"]}** and average contribution count 
            is **{config["total"]["average"]:.2f}**
            - Daily maximum contribution day is **{config["max"]["date"]}**, which is **{config["max"]["count"]}**.
            - Longest continous contribution trip was **{config["continuous"]["max"]["length"]}** days 
            From **{config["continuous"]["max"]["start"]}** to **{config["continuous"]["max"]["end"]}** :walking:
            - Current continous contribution trip is **{config["continuous"]["current"]["length"]}** days 
            From **{config["continuous"]["current"]["start"]}** :running:
        """)

    def config_graph(self) -> ConfigType:
        return {
            "section": {
                "title": "Graph"
            },
            "bar": {
                "count": {
                    "x": "contribution",
                    "y": "day",
                    "sum": {
                        "recent": {
                            "title": "Number of days per contribution up to the last 4 weeks",
                        },
                        "full": {
                            "title": "Number of days per contribution",
                        },
                    },
                },
                "dayofweek": {
                    "label": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                    "x": "day of week",
                    "y": "contribution",
                    "sum": {
                        "recent": {
                            "title": "Number of contribution per day of week up to the last 12 weeks",
                        },
                    },
                    "mean": {
                        "full": {
                            "title": "Average of contribution per day of week",
                        }
                    }
                },
                "month": {
                    "label": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                    "x": "month",
                    "y": "contribution",
                    "sum": {
                        "recent": {
                            "title": "Number of contribution per month up to the last year",
                        },
                    },
                    "mean": {
                        "full": {
                            "title": "Average of contribution per month",
                        },
                    },
                },
            },
            "title": {
                "bar:count:sum:recent": "Number of days per contribution up to the last 4 weeks",
                "bar:count:sum:full": "Number of days per contribution",
                "bar:dayofweek:sum:recent": "Number of contribution per day of week up to the last 12 weeks",
                "bar:dayofweek:mean:full": "Average of contribution per day of week",
                "bar:month:sum:recent": "Number of contribution per month up to the last year",
                "bar:month:mean:full": "Average of contribution per month",
            },
        }
