from lib.language.base import LanguageSetting


class EnglishSetting(LanguageSetting):
    def header_greeting(self, username: str) -> str:
        return f"Welcome to {username}'s contribution report"

    def header_notice(self, repo_url: str, issue_url: str) -> str:
        return f"""
            This report is generated by [contribution-markdown-report]({repo_url}).
            If you have any question or problem, please report [here]({issue_url}).
            I hope this report will be a companion for your contribution trip."""

    def summary_title(self) -> str:
        return "Summary"

    def summary_today(self, today: str, length: str, count: str) -> str:
        return f"{today} was {length}th day since the start of trip, and there was {count} new contribution."

    def summary_maximum(self, date: str, count: str) -> str:
        return f"Daily maximum contribution day is {date}, which is {count}."

    def summary_total(self, sum: str, avg: str) -> str:
        return f"During the trip, total contribuition count is {sum} and average contribution count is {avg}."

    def summary_peak(self, length: str, start: str, end: str) -> str:
        return f"Longest continuous contribution trip was {length} days from {start} to {end}."

    def summary_cur_peak(self, length: str, start: str) -> str:
        return f"Current continuous contribution trip is {length} days from {start}."

    def config_graph(self):
        return {
            "section": {
                "title": "Graph"
            },
            "bar": {
                "count": {
                    "x": "contribution",
                    "y": "day",
                    "sum": {
                        "recent": {
                            "title": "Number of days per contribution up to the last 4 weeks",
                        },
                        "full": {
                            "title": "Number of days per contribution",
                        },
                    },
                },
                "dayofweek": {
                    "label": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                    "x": "day of week",
                    "y": "contribution",
                    "sum": {
                        "recent": {
                            "title": "Number of contribution per day of week up to the last 12 weeks",
                        },
                    },
                    "mean": {
                        "full": {
                            "title": "Average of contribution per day of week",
                        }
                    }
                },
                "month": {
                    "label": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                    "x": "month",
                    "y": "contribution",
                    "sum": {
                        "recent": {
                            "title": "Number of contribution per month up to the last year",
                        },
                    },
                    "mean": {
                        "full": {
                            "title": "Average of contribution per month",
                        },
                    },
                },
            },
            "title": {
                "bar:count:sum:recent": "Number of days per contribution up to the last 4 weeks",
                "bar:count:sum:full": "Number of days per contribution",
                "bar:dayofweek:sum:recent": "Number of contribution per day of week up to the last 12 weeks",
                "bar:dayofweek:mean:full": "Average of contribution per day of week",
                "bar:month:sum:recent": "Number of contribution per month up to the last year",
                "bar:month:mean:full": "Average of contribution per month",
            },
        }
